#ifndef VEHICLE_COMPONENTS_ID_CONFIG_H
#define VEHICLE_COMPONENTS_ID_CONFIG_H

enum vehicle_components_id_config {
    MAIN_COMPUTER,
    IMAGE_INPUT,
    WHEELS,
    BREAKS,
    GAS,
    COMPONENTS_COUNT
};

enum ACTIONS {
    PRESS_BREAKS,
    PRESS_GAS
};

#endif // VEHICLE_COMPONENTS_ID_CONFIG_H
